// Mocks generated by Mockito 5.4.4 from annotations
// in age_estimator/test/features/home/cubit/estimation_age_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:age_estimator/features/home/model/data/estimated_age_model.dart'
    as _i2;
import 'package:age_estimator/features/home/model/repository/estimation_age_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEstimatedAgeModel_0 extends _i1.SmartFake
    implements _i2.EstimatedAgeModel {
  _FakeEstimatedAgeModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EstimationAgeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEstimationAgeRepository extends _i1.Mock
    implements _i3.EstimationAgeRepository {
  MockEstimationAgeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.EstimatedAgeModel> getEstimatedAge(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEstimatedAge,
          [name],
        ),
        returnValue:
            _i4.Future<_i2.EstimatedAgeModel>.value(_FakeEstimatedAgeModel_0(
          this,
          Invocation.method(
            #getEstimatedAge,
            [name],
          ),
        )),
      ) as _i4.Future<_i2.EstimatedAgeModel>);

  @override
  _i4.Future<_i2.EstimatedAgeModel> getEstimatedAgeIsolate(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEstimatedAgeIsolate,
          [name],
        ),
        returnValue:
            _i4.Future<_i2.EstimatedAgeModel>.value(_FakeEstimatedAgeModel_0(
          this,
          Invocation.method(
            #getEstimatedAgeIsolate,
            [name],
          ),
        )),
      ) as _i4.Future<_i2.EstimatedAgeModel>);
}
